self.this_user = false # Deprecated, that's why always false
self.apt_get = true
self.ffmpeg_first = false
self.github_tar = false
self.vendor = false
self.branch = 'edge'
self.threads = 1
self.bootstrap = true
self.configure = true
self.make = true
self.make_install = true
self.only = nil
self.enable_debug = false
self.enable_debug_on = nil